"""Whitelist Auto-Learning Module

Implements local self-learning mechanism for whitelist based on historical scan data.
This module observes clean scan results over time and suggests legitimate programs
to be added to the whitelist.

Learning Process:
1. Observation Window: Records program occurrences from clean scans (default: 30 days)
2. Pattern Analysis: Identifies programs that appear frequently in clean scans
3. Confidence Calculation: Computes confidence score based on occurrence frequency,
   clean scan ratio, and recency
4. Suggestion Generation: Generates whitelist suggestions for user confirmation

Security Considerations:
- Only learns from scans with 'clean' result (no alerts)
- Requires minimum occurrences (default: 5) before suggesting
- Time-bounded observation window prevents stale data accumulation
- All suggestions require manual user confirmation
- Learning data stored locally only (privacy-preserving)
"""
import json
import math
import sqlite3
import logging
from datetime import datetime, timezone, timedelta
from typing import Optional, Dict, List, Set
from .datetime_compat import fromisoformat
from dataclasses import dataclass, asdict
from pathlib import Path

logger = logging.getLogger("sec-userspace")


@dataclass
class ProgramObservation:
    """Represents a single observation of a program during a scan"""
    program_name: str
    program_hash: Optional[str]
    program_path: Optional[str]
    scan_id: str
    scan_result: str  # 'clean' or 'alert'
    observed_at: str  # ISO format timestamp
    module: str  # Which analyzer detected it
    context: Optional[Dict] = None  # Additional context (parent process, cmdline, etc.)


@dataclass
class WhitelistSuggestion:
    """Whitelist suggestion generated by the learning system"""
    tool_name: str
    confidence: float  # 0.0 to 1.0
    reason: str
    first_seen: str  # ISO format
    last_seen: str  # ISO format
    occurrence_count: int
    clean_scan_ratio: float
    status: str = 'pending'  # pending, accepted, rejected
    program_path: Optional[str] = None
    program_hash: Optional[str] = None
    suggested_at: str = ""
    
    def __post_init__(self):
        if not self.suggested_at:
            self.suggested_at = datetime.now(timezone.utc).isoformat()
    
    def to_dict(self) -> dict:
        """Convert to dictionary"""
        return asdict(self)
    
    @classmethod
    def from_dict(cls, data: dict) -> 'WhitelistSuggestion':
        """Create from dictionary"""
        return cls(**data)


class WhitelistLearner:
    """Whitelist auto-learner
    
    Observes programs during clean scans and suggests legitimate programs
    for whitelist inclusion based on historical patterns.
    
    Attributes:
        db_path: Path to SQLite database for storing observations
        observation_window_days: Number of days to look back (default: 30)
        min_occurrences: Minimum times to see a program before suggesting (default: 5)
        confidence_threshold: Minimum confidence for suggestions (default: 0.7)
    """
    
    DEFAULT_OBSERVATION_WINDOW_DAYS = 30
    DEFAULT_MIN_OCCURRENCES = 5
    DEFAULT_CONFIDENCE_THRESHOLD = 0.7
    
    def __init__(
        self,
        workspace_dir: str,
        observation_window_days: int = DEFAULT_OBSERVATION_WINDOW_DAYS,
        min_occurrences: int = DEFAULT_MIN_OCCURRENCES,
        confidence_threshold: float = DEFAULT_CONFIDENCE_THRESHOLD,
    ):
        """Initialize whitelist learner
        
        Args:
            workspace_dir: Workspace directory for storing learning data
            observation_window_days: Days to observe (default: 30)
            min_occurrences: Min occurrences before suggesting (default: 5)
            confidence_threshold: Min confidence for suggestions (default: 0.7)
        """
        self.workspace_dir = Path(workspace_dir)
        self.observation_window_days = observation_window_days
        self.min_occurrences = min_occurrences
        self.confidence_threshold = confidence_threshold
        
        # Create learning directory
        self.learning_dir = self.workspace_dir / "learning"
        self.learning_dir.mkdir(parents=True, exist_ok=True)
        
        # Initialize SQLite database
        self.db_path = self.learning_dir / "observations.db"
        self._init_db()
        
        # Suggestions storage
        self.suggestions_path = self.learning_dir / "suggestions.json"
        self._suggestions: List[WhitelistSuggestion] = []
        self._load_suggestions()
    
    def _init_db(self) -> None:
        """Initialize SQLite database schema"""
        conn = sqlite3.connect(str(self.db_path))
        try:
            cursor = conn.cursor()

            cursor.execute("""
                CREATE TABLE IF NOT EXISTS program_observations (
                    id INTEGER PRIMARY KEY AUTOINCREMENT,
                    program_name TEXT NOT NULL,
                    program_hash TEXT,
                    program_path TEXT,
                    scan_id TEXT NOT NULL,
                    scan_result TEXT NOT NULL,
                    module TEXT NOT NULL,
                    observed_at TIMESTAMP NOT NULL,
                    context TEXT,
                    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
                )
            """)

            cursor.execute("""
                CREATE INDEX IF NOT EXISTS idx_program_name
                ON program_observations(program_name)
            """)
            cursor.execute("""
                CREATE INDEX IF NOT EXISTS idx_observed_at
                ON program_observations(observed_at)
            """)
            cursor.execute("""
                CREATE INDEX IF NOT EXISTS idx_scan_result
                ON program_observations(scan_result)
            """)
            cursor.execute("""
                CREATE INDEX IF NOT EXISTS idx_module
                ON program_observations(module)
            """)

            cursor.execute("""
                CREATE TABLE IF NOT EXISTS suggestions (
                    id INTEGER PRIMARY KEY AUTOINCREMENT,
                    tool_name TEXT NOT NULL UNIQUE,
                    confidence REAL NOT NULL,
                    reason TEXT,
                    first_seen TIMESTAMP NOT NULL,
                    last_seen TIMESTAMP NOT NULL,
                    occurrence_count INTEGER NOT NULL,
                    clean_scan_ratio REAL NOT NULL,
                    status TEXT DEFAULT 'pending',
                    program_path TEXT,
                    program_hash TEXT,
                    suggested_at TIMESTAMP NOT NULL,
                    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
                )
            """)

            conn.commit()
        finally:
            conn.close()
    
    def record_scan(
        self,
        scan_id: str,
        scan_result: str,
        programs: List[Dict],
        module: str = "ebpf_analyzer",
    ) -> int:
        """Record scan result for learning
        
        Args:
            scan_id: Unique scan identifier
            scan_result: Scan result ('clean' or 'alert')
            programs: List of program dictionaries with keys:
                     - name: Program name
                     - hash: Program hash (optional)
                     - path: Program path (optional)
                     - context: Additional context (optional)
            module: Analyzer module name
            
        Returns:
            int: Number of programs recorded
        """
        if scan_result != 'clean':
            # Only learn from clean scans
            logger.debug(f"Skipping learning from scan {scan_id} with result: {scan_result}")
            return 0
        
        conn = sqlite3.connect(str(self.db_path))
        try:
            cursor = conn.cursor()

            observed_at = datetime.now(timezone.utc).isoformat()
            count = 0

            for prog in programs:
                cursor.execute("""
                    INSERT INTO program_observations
                    (program_name, program_hash, program_path, scan_id, scan_result,
                     module, observed_at, context)
                    VALUES (?, ?, ?, ?, ?, ?, ?, ?)
                """, (
                    prog.get('name', 'unknown'),
                    prog.get('hash'),
                    prog.get('path'),
                    scan_id,
                    scan_result,
                    module,
                    observed_at,
                    json.dumps(prog.get('context')) if prog.get('context') else None,
                ))
                count += 1

            conn.commit()
        finally:
            conn.close()

        logger.debug(f"Recorded {count} programs from clean scan {scan_id}")
        return count
    
    def analyze_history(self) -> Dict[str, Dict]:
        """Analyze scan history to identify legitimate programs
        
        Returns:
            Dict mapping program names to statistics:
            - occurrence_count: Total occurrences
            - clean_count: Occurrences in clean scans
            - alert_count: Occurrences in scans with alerts
            - first_seen: First observation timestamp
            - last_seen: Last observation timestamp
            - paths: Set of observed paths
            - avg_confidence: Average confidence score
        """
        conn = sqlite3.connect(str(self.db_path))
        try:
            cursor = conn.cursor()

            cutoff_date = (
                datetime.now(timezone.utc) -
                timedelta(days=self.observation_window_days)
            ).isoformat()

            cursor.execute("""
                SELECT
                    program_name,
                    COUNT(*) as occurrence_count,
                    SUM(CASE WHEN scan_result = 'clean' THEN 1 ELSE 0 END) as clean_count,
                    SUM(CASE WHEN scan_result = 'alert' THEN 1 ELSE 0 END) as alert_count,
                    MIN(observed_at) as first_seen,
                    MAX(observed_at) as last_seen,
                    GROUP_CONCAT(DISTINCT program_path) as paths
                FROM program_observations
                WHERE observed_at >= ?
                GROUP BY program_name
                HAVING occurrence_count >= ?
                ORDER BY occurrence_count DESC
            """, (cutoff_date, self.min_occurrences))

            results = {}
            for row in cursor.fetchall():
                program_name = row[0]
                occurrence_count = row[1]
                clean_count = row[2]
                alert_count = row[3]
                first_seen = row[4]
                last_seen = row[5]
                paths_str = row[6]

                paths = set(paths_str.split(',')) if paths_str else set()
                clean_ratio = clean_count / occurrence_count if occurrence_count > 0 else 0.0

                results[program_name] = {
                    'occurrence_count': occurrence_count,
                    'clean_count': clean_count,
                    'alert_count': alert_count,
                    'first_seen': first_seen,
                    'last_seen': last_seen,
                    'paths': list(paths),
                    'clean_scan_ratio': clean_ratio,
                }
        finally:
            conn.close()

        return results
    
    def calculate_confidence(self, program_name: str) -> float:
        """Calculate confidence score for a program
        
        Confidence is computed as a weighted average of:
        - Occurrence frequency (40%): More occurrences = higher confidence
        - Clean scan ratio (40%): Higher ratio of clean scans = higher confidence
        - Recency (20%): More recent observations = higher confidence
        
        Args:
            program_name: Program name
            
        Returns:
            float: Confidence score between 0.0 and 1.0
        """
        conn = sqlite3.connect(str(self.db_path))
        try:
            cursor = conn.cursor()

            cutoff_date = (
                datetime.now(timezone.utc) -
                timedelta(days=self.observation_window_days)
            ).isoformat()

            cursor.execute("""
                SELECT
                    COUNT(*) as occurrence_count,
                    SUM(CASE WHEN scan_result = 'clean' THEN 1 ELSE 0 END) as clean_count,
                    MAX(observed_at) as last_seen
                FROM program_observations
                WHERE program_name = ? AND observed_at >= ?
            """, (program_name, cutoff_date))

            row = cursor.fetchone()
        finally:
            conn.close()

        if not row or row[0] == 0:
            return 0.0
        
        occurrence_count = row[0]
        clean_count = row[1]
        last_seen_str = row[2]
        
        # Normalize occurrence count (cap at min_occurrences * 3 for max score)
        max_occurrences = self.min_occurrences * 3
        occurrence_score = min(1.0, occurrence_count / max_occurrences)
        
        # Clean scan ratio
        clean_ratio = clean_count / occurrence_count if occurrence_count > 0 else 0.0
        
        # Recency score (exponential decay)
        if last_seen_str:
            try:
                last_seen = fromisoformat(last_seen_str)
                days_since_last_seen = (datetime.now(timezone.utc) - last_seen).days
                # Half-life of 7 days
                recency_score = 0.5 ** (days_since_last_seen / 7.0)
            except (ValueError, TypeError):
                recency_score = 0.0
        else:
            recency_score = 0.0
        
        # Weighted average
        confidence = (
            0.4 * occurrence_score +
            0.4 * clean_ratio +
            0.2 * recency_score
        )
        
        return min(1.0, max(0.0, confidence))
    
    def generate_suggestions(
        self,
        current_whitelist: Optional[Set[str]] = None
    ) -> List[WhitelistSuggestion]:
        """Generate whitelist suggestions
        
        Args:
            current_whitelist: Set of already whitelisted program names
            
        Returns:
            List of whitelist suggestions sorted by confidence (descending)
        """
        if current_whitelist is None:
            current_whitelist = set()
        
        # Analyze history
        stats = self.analyze_history()
        
        suggestions = []
        for program_name, program_stats in stats.items():
            # Skip if already whitelisted
            if program_name in current_whitelist:
                continue
            
            # Calculate confidence
            confidence = self.calculate_confidence(program_name)
            
            # Skip if below threshold
            if confidence < self.confidence_threshold:
                continue
            
            # Generate reason
            reason = (
                f"Observed {program_stats['occurrence_count']} times in "
                f"{program_stats['clean_count']} clean scans "
                f"(ratio: {program_stats['clean_scan_ratio']:.1%})"
            )
            
            # Get program path and hash from latest observation
            program_path = program_stats['paths'][0] if program_stats['paths'] else None
            
            suggestion = WhitelistSuggestion(
                tool_name=program_name,
                confidence=confidence,
                reason=reason,
                first_seen=program_stats['first_seen'],
                last_seen=program_stats['last_seen'],
                occurrence_count=program_stats['occurrence_count'],
                clean_scan_ratio=program_stats['clean_scan_ratio'],
                program_path=program_path,
            )
            
            suggestions.append(suggestion)
        
        suggestions.sort(key=lambda s: s.confidence if not math.isnan(s.confidence) else 0.0, reverse=True)
        
        return suggestions
    
    def accept_suggestion(self, tool_name: str) -> bool:
        """Mark a suggestion as accepted
        
        Args:
            tool_name: Name of the tool to accept
            
        Returns:
            bool: True if suggestion was found and accepted
        """
        conn = sqlite3.connect(str(self.db_path))
        cursor = conn.cursor()
        
        try:
            # First check if suggestion exists
            cursor.execute("""
                SELECT confidence FROM suggestions
                WHERE tool_name = ?
            """, (tool_name,))
            
            row = cursor.fetchone()
            
            if row is not None:
                # Update existing suggestion
                cursor.execute("""
                    UPDATE suggestions
                    SET status = 'accepted', updated_at = ?
                    WHERE tool_name = ?
                """, (datetime.now(timezone.utc).isoformat(), tool_name))
            else:
                # Insert new accepted suggestion with default values
                cursor.execute("""
                    INSERT INTO suggestions 
                    (tool_name, confidence, reason, first_seen, last_seen,
                     occurrence_count, clean_scan_ratio, status, suggested_at, updated_at)
                    VALUES (?, 0.0, 'Manually accepted', ?, ?, 0, 0.0, 'accepted', ?, ?)
                """, (
                    tool_name,
                    datetime.now(timezone.utc).isoformat(),
                    datetime.now(timezone.utc).isoformat(),
                    datetime.now(timezone.utc).isoformat(),
                    datetime.now(timezone.utc).isoformat(),
                ))
            
            conn.commit()
            success = True
        except (sqlite3.Error, OSError) as e:
            logger.error(f"Failed to accept suggestion for {tool_name}: {e}")
            success = False
        finally:
            conn.close()
        
        # Reload suggestions
        self._load_suggestions()
        
        return success
    
    def reject_suggestion(self, tool_name: str) -> bool:
        """Mark a suggestion as rejected
        
        Args:
            tool_name: Name of the tool to reject
            
        Returns:
            bool: True if suggestion was found and rejected
        """
        conn = sqlite3.connect(str(self.db_path))
        cursor = conn.cursor()
        
        try:
            cursor.execute("""
                UPDATE suggestions
                SET status = 'rejected', updated_at = ?
                WHERE tool_name = ?
            """, (datetime.now(timezone.utc).isoformat(), tool_name))
            
            conn.commit()
            success = cursor.rowcount > 0
        except (sqlite3.Error, OSError) as e:
            logger.error(f"Failed to reject suggestion for {tool_name}: {e}")
            success = False
        finally:
            conn.close()
        
        # Reload suggestions
        self._load_suggestions()
        
        return success
    
    def save_suggestions(self, suggestions: List[WhitelistSuggestion]) -> None:
        """Save suggestions to file and database
        
        Args:
            suggestions: List of suggestions to save
        """
        # Save to JSON file
        with open(self.suggestions_path, 'w', encoding='utf-8') as f:
            json.dump(
                [s.to_dict() for s in suggestions],
                f,
                indent=2,
                ensure_ascii=False
            )
        
        conn = sqlite3.connect(str(self.db_path))
        try:
            cursor = conn.cursor()

            for sug in suggestions:
                cursor.execute("""
                    INSERT OR REPLACE INTO suggestions
                    (tool_name, confidence, reason, first_seen, last_seen,
                     occurrence_count, clean_scan_ratio, status, program_path,
                     program_hash, suggested_at, updated_at)
                    VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
                """, (
                    sug.tool_name,
                    sug.confidence,
                    sug.reason,
                    sug.first_seen,
                    sug.last_seen,
                    sug.occurrence_count,
                    sug.clean_scan_ratio,
                    sug.status,
                    sug.program_path,
                    sug.program_hash,
                    sug.suggested_at,
                    datetime.now(timezone.utc).isoformat(),
                ))

            conn.commit()
        finally:
            conn.close()
        
        self._suggestions = suggestions
    
    def _load_suggestions(self) -> None:
        """Load suggestions from database"""
        conn = sqlite3.connect(str(self.db_path))
        try:
            cursor = conn.cursor()

            cursor.execute("""
                SELECT tool_name, confidence, reason, first_seen, last_seen,
                       occurrence_count, clean_scan_ratio, status, program_path,
                       program_hash, suggested_at
                FROM suggestions
                ORDER BY confidence DESC
            """)

            self._suggestions = []
            for row in cursor.fetchall():
                suggestion = WhitelistSuggestion(
                    tool_name=row[0],
                    confidence=row[1],
                    reason=row[2],
                    first_seen=row[3],
                    last_seen=row[4],
                    occurrence_count=row[5],
                    clean_scan_ratio=row[6],
                    status=row[7],
                    program_path=row[8],
                    program_hash=row[9],
                    suggested_at=row[10],
                )
                self._suggestions.append(suggestion)
        finally:
            conn.close()
    
    def get_suggestions(self, status: Optional[str] = None) -> List[WhitelistSuggestion]:
        """Get stored suggestions
        
        Args:
            status: Filter by status (pending, accepted, rejected) or None for all
            
        Returns:
            List of suggestions matching the filter
        """
        if status is None:
            return self._suggestions.copy()
        
        return [s for s in self._suggestions if s.status == status]
    
    def cleanup_old_data(self, max_age_days: int = 90) -> int:
        """Clean up old observation data

        Args:
            max_age_days: Maximum age of data to keep (default: 90 days)

        Returns:
            int: Number of records deleted
        """
        conn = sqlite3.connect(str(self.db_path))
        try:
            cursor = conn.cursor()

            cutoff_date = (
                datetime.now(timezone.utc) -
                timedelta(days=max_age_days)
            ).isoformat()

            cursor.execute("""
                DELETE FROM program_observations
                WHERE observed_at < ?
            """, (cutoff_date,))

            deleted = cursor.rowcount
            conn.commit()
        finally:
            conn.close()

        conn2 = sqlite3.connect(str(self.db_path))
        try:
            conn2.execute("VACUUM")
        finally:
            conn2.close()
        
        logger.info(f"Cleaned up {deleted} old observation records")
        return deleted
    
    def get_stats(self) -> Dict:
        """Get learning statistics

        Returns:
            Dict containing learning statistics
        """
        conn = sqlite3.connect(str(self.db_path))
        try:
            cursor = conn.cursor()

            cursor.execute("SELECT COUNT(*) FROM program_observations")
            total_observations = cursor.fetchone()[0]

            cutoff_date = (
                datetime.now(timezone.utc) -
                timedelta(days=self.observation_window_days)
            ).isoformat()
            cursor.execute("""
                SELECT COUNT(*) FROM program_observations
                WHERE observed_at >= ?
            """, (cutoff_date,))
            window_observations = cursor.fetchone()[0]

            cursor.execute("""
                SELECT COUNT(DISTINCT program_name) FROM program_observations
                WHERE observed_at >= ?
            """, (cutoff_date,))
            unique_programs = cursor.fetchone()[0]

            cursor.execute("""
                SELECT scan_result, COUNT(*) FROM program_observations
                WHERE observed_at >= ?
                GROUP BY scan_result
            """, (cutoff_date,))
            scan_results = dict(cursor.fetchall())
        finally:
            conn.close()

        pending = sum(1 for s in self._suggestions if s.status == 'pending')
        accepted = sum(1 for s in self._suggestions if s.status == 'accepted')
        rejected = sum(1 for s in self._suggestions if s.status == 'rejected')
        
        return {
            'total_observations': total_observations,
            'window_observations': window_observations,
            'unique_programs_in_window': unique_programs,
            'clean_observations': scan_results.get('clean', 0),
            'alert_observations': scan_results.get('alert', 0),
            'suggestions': {
                'pending': pending,
                'accepted': accepted,
                'rejected': rejected,
            },
            'observation_window_days': self.observation_window_days,
            'min_occurrences': self.min_occurrences,
            'confidence_threshold': self.confidence_threshold,
        }
    
    def clear_learning_data(self) -> int:
        """Clear all learning data

        Returns:
            int: Number of records deleted
        """
        conn = sqlite3.connect(str(self.db_path))
        try:
            cursor = conn.cursor()

            cursor.execute("DELETE FROM program_observations")
            deleted_obs = cursor.rowcount

            cursor.execute("DELETE FROM suggestions")
            deleted_sug = cursor.rowcount

            conn.commit()
        finally:
            conn.close()
        
        # Remove suggestions file
        if self.suggestions_path.exists():
            self.suggestions_path.unlink()
        
        self._suggestions = []
        
        logger.info(
            f"Cleared {deleted_obs} observations and {deleted_sug} suggestions"
        )
        return deleted_obs + deleted_sug


def get_learner(workspace_dir: str) -> WhitelistLearner:
    """Get whitelist learner instance
    
    Args:
        workspace_dir: Workspace directory
        
    Returns:
        WhitelistLearner instance
    """
    return WhitelistLearner(workspace_dir)
