#!/usr/bin/env python3
"""Cloud Firewall backup tool - main entry point"""

import argparse
import os
import sys
from datetime import datetime
from core import BackupEngine, load_default_credentials
from address_book import list_plugins as list_address_book_plugins
from address_book import get_plugins as get_address_book_plugins
from address_book import get_all_plugin_names as get_address_book_plugin_names
from acl_policy import list_plugins as list_acl_policy_plugins
from acl_policy import get_plugins as get_acl_policy_plugins
from acl_policy import get_all_plugin_names as get_acl_policy_plugin_names


def main():
    parser = argparse.ArgumentParser(description="Cloud Firewall backup tool (address books + ACL policies)")
    parser.add_argument("--list", action="store_true", help="List all available backup types")
    parser.add_argument("--types", nargs="+", help="Types to back up/restore (multiple allowed, supports address books and ACL policies)")
    parser.add_argument("--region", default="cn-hangzhou", help="Alibaba Cloud region (default cn-hangzhou)")
    parser.add_argument("--output", help="Output file name (auto-generated by default)")
    parser.add_argument("--input", help="Input file name for restore (the latest backup file is used by default)")
    parser.add_argument("--mode", choices=["append", "diff"], default="append",
                        help="Restore mode: append=append mode (default, restores to a new account or different "
                             "target resources, rewrite resource IDs together with --nat-target-gateways/"
                             "--vpc-target-groups); diff=differential restore, only restores configurations "
                             "missing online (only applicable when restoring to the same resources as the "
                             "backup source)")
    parser.add_argument("--yes", action="store_true", help="Skip the interactive confirmation of the restore order warning (auto-continues by default in non-interactive environments)")
    parser.add_argument("--nat-target-gateways", help="Target NAT gateways specified by the user when restoring "
                                                      "the Internet boundary NAT firewall (comma-separated, multiple "
                                                      "allowed; policies are broadcast-restored to each gateway). "
                                                      "Takes priority when specified in append mode: policy resource "
                                                      "IDs are rewritten to the target gateways, applicable to both "
                                                      "gateway-swap-in-same-account and cross-account scenarios")
    parser.add_argument("--vpc-target-groups", help="Target policy group IDs specified by the user when restoring "
                                                     "the VPC boundary (comma-separated, multiple allowed; policies "
                                                     "are broadcast-restored to each policy group). Takes priority "
                                                     "when specified in append mode: policy resource IDs are "
                                                     "rewritten to the target policy groups, applicable to both "
                                                     "policy-group-swap-in-same-account and cross-account scenarios")
    
    args = parser.parse_args()

    # Scenario conflict validation: differential restore only applies to "restoring to the same
    # resources as the backup source" (same gateway/policy group, only filling missing items),
    # and is mutually exclusive with "rewriting to other target resources"; restoring to different
    # target resources must use append mode with explicit target specification.
    if args.mode == "diff" and (args.nat_target_gateways or args.vpc_target_groups):
        print("[FAIL] --mode diff cannot be used together with --nat-target-gateways/--vpc-target-groups:")
        print("   Differential restore only applies to restoring to the same resources as the backup source (same gateway/policy group, only filling missing items);")
        print("   To restore to other gateways/policy groups (same account or cross-account), use --mode append (default) and specify the target resources.")
        return
    
    # --list does not require credentials; list all plugins directly
    if args.list:
        ab_plugins = list_address_book_plugins()
        acl_plugins = list_acl_policy_plugins()
        
        print("\n")
        print("=" * 60)
        print("[WARN] User notice")
        print("=" * 60)
        print("\n")
        print("  1. This skill supports backup and restore of address books and ACL policy configurations.")
        print("\n")
        print("  2. Backup of application control templates and web filtering templates is NOT supported.")
        print("     If configured, they must be backed up and restored manually.")
        print("\n")
        print("  3. Restore order requirements (configurations have reference dependencies):")
        print("     Step 1: Manually restore application control templates and web filtering templates (if enabled)")
        print("     Step 2: Restore sync nodes (ACK clusters + private DNS) -> options 2, 3")
        print("     Step 3: Restore other address book configurations -> options 4, 5, 6, 7")
        print("     Step 4: Restore ACL policies -> options 8, 9, 10")
        print("\n")
        print("  [WARN] Violating the order may cause restore failure!")
        print("\n")
        print("  4. Special notes:")
        print("     - Address books do not allow duplicate names; restoring a duplicate name will raise an error and be marked as already existing.")
        print("     - ACL policies allow duplicate names; restore only performs append and never modifies existing policies.")
        print("       All restored ACL policies are inserted at the end. Please check the policy order after restore completes.")
        print("\n")
        print("=" * 60)
        print("[Backup]")
        print("=" * 60)
        print("\n")
        print("  Option 1: Back up all configurations (address books + ACL policies)")
        print("\n")
        
        print("=" * 60)
        print("[Restore - restore address book configurations]")
        print("=" * 60)
        print("\n")
        idx = 2
        for plugin in ab_plugins:
            print(f"  Option {idx}: {plugin.name}")
            print("\n")
            idx += 1
        
        print("=" * 60)
        print("[Restore - restore ACL policy configurations]")
        print("=" * 60)
        print("\n")
        for plugin in acl_plugins:
            print(f"  Option {idx}: {plugin.name}")
            print("\n")
            idx += 1
        
        print("=" * 60)
        print("[Restore - restore all address books + ACL]")
        print("=" * 60)
        print("\n")
        print(f"  Option {idx}: Restore all address books + ACL")
        print("\n")
        print("=" * 60)
        print("\n")
        return
    
    # Load credentials (default credential chain; only checked when actually backing up/restoring)
    access_key_id, access_key_secret, security_token = load_default_credentials()
    
    if not args.types:
        print("Error: no backup type specified. Use --list to view available types, or specify them with --types")
        return
    
    # Build the mapping from option index to plugin name
    ab_plugins = list_address_book_plugins()
    acl_plugins = list_acl_policy_plugins()
    idx_to_name = {}
    
    # Backup option
    idx_to_name["1"] = ("special", "备份全部配置（地址簿 + ACL策略）")
    
    # Restore options
    idx = 2
    for plugin in ab_plugins:
        idx_to_name[str(idx)] = ("restore_address_book", plugin.name)
        idx += 1
    for plugin in acl_plugins:
        idx_to_name[str(idx)] = ("restore_acl_policy", plugin.name)
        idx += 1
    idx_to_name[str(idx)] = ("special", "恢复所有配置(地址簿+ACL策略)")
    
    # Convert the input types to plugin names (both numeric indices and names are supported)
    resolved_types = []
    for type_name in args.types:
        if type_name in idx_to_name:
            _, name = idx_to_name[type_name]
            resolved_types.append(name)
        else:
            resolved_types.append(type_name)
    
    # Separate address books and ACL policies
    address_book_names = []
    acl_policy_names = []
    
    all_address_book = get_address_book_plugin_names()
    all_acl_policy = get_acl_policy_plugin_names()
    
    # Handle special options
    backup_all = "备份全部配置（地址簿 + ACL策略）" in resolved_types
    restore_all = "恢复所有配置(地址簿+ACL策略)" in resolved_types
    
    # Categorize
    restore_address_book_names = []
    restore_acl_policy_names = []
    
    if backup_all:
        # Perform backup operation
        address_book_names = all_address_book
        acl_policy_names = all_acl_policy
    elif restore_all:
        # Restore all configurations
        restore_address_book_names = all_address_book
        restore_acl_policy_names = all_acl_policy
    else:
        for type_name in resolved_types:
            # Skip special options
            if type_name in ["备份全部配置（地址簿 + ACL策略）", "恢复所有配置(地址簿+ACL策略)"]:
                continue
            
            # Check whether it is a restore operation
            if type_name in all_address_book:
                restore_address_book_names.append(type_name)
            elif type_name in all_acl_policy:
                restore_acl_policy_names.append(type_name)
            else:
                print(f"Warning: unknown type '{type_name}', skipped")
    
    # Determine the operation type
    is_backup = backup_all
    is_restore = restore_all or restore_address_book_names or restore_acl_policy_names
    
    if is_backup:
        # Generate the output file name (write to the current directory or the path specified by --output)
        if args.output:
            output_file = args.output
        else:
            output_file = f"cfw_policy_backup_{datetime.now().strftime('%y%m%d')}.xlsx"

        # Ensure the output directory exists
        output_dir = os.path.dirname(os.path.abspath(output_file))
        os.makedirs(output_dir, exist_ok=True)

        print(f"Starting backup to: {output_file}")
        print(f"Region: {args.region}")
        
        # Create the backup engine
        engine = BackupEngine(access_key_id, access_key_secret, args.region,
                              security_token=security_token)
        
        # Back up address books
        if address_book_names:
            print(f"\nBacking up address books: {', '.join(address_book_names)}")
            plugins = get_address_book_plugins(address_book_names)
            engine.backup_to_excel(plugins, output_file, append=False)
        
        # Back up ACL policies
        if acl_policy_names:
            print(f"\nBacking up ACL policies: {', '.join(acl_policy_names)}")
            plugins = get_acl_policy_plugins(acl_policy_names)
            engine.backup_to_excel(plugins, output_file, append=True)
        
        print(f"\nBackup completed: {output_file}")
    
    elif is_restore:
        # Restore order validation
        # Sync nodes (ACK clusters, private DNS) = options 2, 3
        # Other address books (custom IP, cloud asset IP, custom domain, port) = options 4, 5, 6, 7
        # ACL policies (Internet boundary, NAT boundary, VPC boundary) = options 8, 9, 10
        sync_node_names = ["同步节点-ACK集群", "同步节点-私有DNS"]
        other_ab_names = ["自定义IP", "云资产IP", "自定义域名", "端口"]
        acl_names = ["互联网边界", "NAT边界", "VPC边界"]

        has_sync = any(n in restore_address_book_names for n in sync_node_names)
        has_other_ab = any(n in restore_address_book_names for n in other_ab_names)
        has_acl = bool(restore_acl_policy_names)

        if restore_all:
            # When restoring all, remind the user of the order
            print("\n[WARN] Restore order reminder:")
            print("  Restoring all configurations runs in the correct order: sync nodes -> other address books -> ACL policies")
            print("  Please make sure application control templates and web filtering templates have been restored manually (if enabled).\n")
        else:
            # Check whether the order is violated
            order_warnings = []
            if has_acl and not has_sync and not has_other_ab:
                order_warnings.append("  [WARN] You are restoring ACL policies without restoring sync nodes and address books.")
                order_warnings.append("     ACL policies may reference address books that have not been restored yet. Restore address books (options 2-7) first.")
            if has_other_ab and not has_sync:
                order_warnings.append("  [WARN] You are restoring address books without restoring sync nodes.")
                order_warnings.append("     Restore sync nodes (options 2, 3) first, then restore other address books (options 4-7).")

            if order_warnings:
                print("\n" + "=" * 60)
                print("[WARN] Restore order warning")
                print("=" * 60)
                for w in order_warnings:
                    print(w)
                print("\n  Correct restore order:")
                print("    Step 1: Manually restore application control templates and web filtering templates (if enabled)")
                print("    Step 2: Restore sync nodes (ACK clusters + private DNS) -> options 2, 3")
                print("    Step 3: Restore other address book configurations -> options 4, 5, 6, 7")
                print("    Step 4: Restore ACL policies -> options 8, 9, 10")
                print("=" * 60)
                print()

                # Interactive confirmation: only ask in interactive terminals; --yes or
                # non-interactive environments continue directly (avoid blocking)
                if not args.yes and sys.stdin.isatty():
                    confirm = input("  Continue restore? (y/n)").strip().lower()
                    if confirm != 'y':
                        print("Restore operation cancelled.")
                        return
                else:
                    print("  [INFO] Order warning acknowledged, continuing restore (--yes or non-interactive environment)")
                print()

        # Determine the input file
        if args.input:
            input_file = args.input
        else:
            # Find the latest backup file (current directory and historical sandbox directories)
            import glob
            candidates = (
                glob.glob("cfw_policy_backup_*.xlsx")
                + glob.glob("/home/sandbox/workspace/files/cfw_policy_backup_*.xlsx")
            )
            backup_files = sorted(candidates, reverse=True)
            if not backup_files:
                print("[FAIL] No backup file found. Please specify the backup file with the --input parameter")
                return
            input_file = backup_files[0]
        
        if not os.path.exists(input_file):
            print(f"[FAIL] Backup file does not exist: {input_file}")
            return
        
        print(f"Starting restore from backup file: {input_file}")
        print(f"Region: {args.region}")
        
        # Import the call_api function from the core module
        from core import call_api

        if args.mode == "diff":
            from diff_restore import diff_restore
            print("\n[INFO] Differential restore mode: compare with live configurations first and only restore missing items (address books are idempotent server-side and still go through regular restore)")
        
        # Restore address books
        if restore_address_book_names:
            plugins = get_address_book_plugins(restore_address_book_names)
            for plugin in plugins:
                print(f"\n{'='*60}")
                print(f"Restoring: {plugin.name}")
                print(f"{'='*60}")
                plugin.restore(
                    ak=access_key_id,
                    sk=access_key_secret,
                    region=args.region,
                    call_api_fn=call_api,
                    excel_file=input_file,
                    security_token=security_token
                )
        
        # Restore ACL policies
        if restore_acl_policy_names:
            # Target resource selection parameters (when restoring cross-account, the gateways/policy
            # groups in the backup do not exist; the user specifies targets, multiple allowed, broadcast)
            nat_targets = [t.strip() for t in args.nat_target_gateways.split(",")] \
                if getattr(args, "nat_target_gateways", None) else None
            vpc_targets = [t.strip() for t in args.vpc_target_groups.split(",")] \
                if getattr(args, "vpc_target_groups", None) else None
            plugins = get_acl_policy_plugins(restore_acl_policy_names)
            for plugin in plugins:
                print(f"\n{'='*60}")
                print(f"Restoring: {plugin.name}")
                print(f"{'='*60}")
                if args.mode == "diff":
                    diff_restore(
                        plugin=plugin,
                        excel_file=input_file,
                        ak=access_key_id,
                        sk=access_key_secret,
                        region=args.region,
                        apply=True,
                        security_token=security_token,
                    )
                else:
                    extra_kwargs = {}
                    if plugin.name == "NAT边界" and nat_targets:
                        extra_kwargs["nat_target_gateways"] = nat_targets
                    if plugin.name == "VPC边界" and vpc_targets:
                        extra_kwargs["vpc_target_groups"] = vpc_targets
                    plugin.restore(
                        ak=access_key_id,
                        sk=access_key_secret,
                        region=args.region,
                        call_api_fn=call_api,
                        excel_file=input_file,
                        security_token=security_token,
                        **extra_kwargs
                    )

        if args.mode == "diff" and restore_acl_policy_names:
            print("\n[OK] Differential restore completed. You can run the same command again to re-check (expected missing count is 0)")
    
    else:
        print("[FAIL] No valid operation type specified")
        return


if __name__ == "__main__":
    main()
